image: python:3.8-slim-buster

before_script:
  - python --version
  - pip install ".[dev]"

stages:
 - Static Analysis
 - Test
 - Build
 - Publish

mypy:
  stage: Static Analysis
  script:
    - python -m mypy src/minio_keygen/*.py

flake8:
  stage: Static Analysis
  script:
    - flake8 --statistics --count --max-line-length=130 --max-complexity 8 src/minio_keygen/*.py

pylint:
  stage: Static Analysis
  allow_failure: true
  script:
    - pylint -d C0301 src/minio_keygen/*.py

safety:
  stage: Static Analysis
  script:
    - safety check

pytest:
  stage: Test
  script:
    - py.test --verbose

coverage:
  stage: Test
  allow_failure: true
  script:
    - pytest --cov minio_keygen

build:
  stage: Build
  script:
    - python -m build
  artifacts:
    paths:
      - dist/*
    expire_in: 1 week

publish-dev:
  stage: Publish
  script:
    - pip install twine
    - twine check dist/*
    - twine upload --skip-existing --repository testpypi -u $PYPI_USERNAME -p $PYPI_PASSWORD dist/*
  only:
    - development

publish-prod:
  stage: Publish
  script:
    - pip install twine
    - twine check dist/*
    - twine upload --skip-existing -u $PYPI_USERNAME -p $PYPI_PASSWORD dist/*
  only:
    - main
