name: Pylint

on: 
  push:
    branches-ignore:
      - 'main'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]#, "3.9", "3.8"]
    steps:
    - uses: actions/checkout@v3.3.0
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4.5.0
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install ".[dev]"
    
    - name: "Static analysis: pylint"
      run: |
        pylint -d C0301 $(git ls-files '*.py')

    - name: "Static analysis: mypy"
      run: |
        python -m mypy src/minio_keygen/*.py

    - name: "Static analysis: flake8"
      run: |
        flake8 --statistics --count --max-line-length=130 --max-complexity 8 src/minio_keygen/*.py

    - name: "Static analysis: safety"
      run: |
        safety check

    - name: "Test: pytest"
      run: |
        py.test --verbose

    - name: "Test: coverage"
      run: |
        pytest --cov minio_keygen

    - name: Build package
      run: python -m build

    - name: Archive package
      uses: actions/upload-artifact@v3
      with:
        name: minio_keygen
        path: dist/
